# Imports

In [1]:
import numpy as np 
import pandas as pd 
import os
from mggp import MGGP

# Execute

In [8]:
dataframes = []

for RT_data in os.listdir('RT_datas'):
    print(f"Lendo o arquivo: {RT_data}")
    data = pd.read_csv(f"RT_datas/{RT_data}")
    data_selected  = data[['ch_AngleSlip____', 'ch_VelLocalX_m_s_', 'ch_VelLocalY_m_s_']]
    dataframes.append(data_selected)

df_result = pd.concat(dataframes, ignore_index=True).fillna(0)
df_result.columns = ['AngleSlip', 'Vx', 'Vy']
# df_result = df_result.sample(frac=1, random_state=42).reset_index(drop=True) # Lines randomized
df_result.to_csv("angle_slip.csv", index=False)

Lendo o arquivo: RT_data_Job1_2023_07_28_16_41_10_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_36_05_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_41_22_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_46_44_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_58_50_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_12_15_29_Mix.csv


In [2]:
df_train = pd.read_csv("angle_slip.csv").to_numpy()
u, y = (df_train[:, :2], df_train[:, 2:3])

split = 0.8
y_train = y[:int(len(y)*split)]
y_val = y[int(len(y)*split):]

print(len(y_val), len(y_train))

u_train = u[:int(len(u)*split)]
u_val = u[int(len(u)*split):]

print(len(u_val), len(u_train))

60689 242753
60689 242753


In [ ]:
mggp = MGGP(inputs=u_train,
            outputs=y_train,
            validation=(u_val, y_val),
            #nDelays=[1, 2, 3, 5, 10, 15, 25, 50],
            nDelays=15,
            generations=1,
            evaluationMode="RMSE",
            k=100,
            evaluationType="MShooting")

mggp.run()

Evaluating Initial Population:   0%|          | 0/100 [00:27<?, ?it/s]


In [11]:
mggp = MGGP(inputs=u_train,
            outputs=y_train,
            validation=(u_val, y_val),
            #nDelays=[1, 2, 3, 5, 10, 15, 25, 50],
            nDelays=15,
            generations=20,
            evaluationMode="RMSE",
            k=100,
            evaluationType="MShooting")

mggp.run()

Evaluating Initial Population: 100%|██████████| 100/100 [02:29<00:00,  1.50s/it]

   	     	          fitness          
   	     	---------------------------
gen	evals	min     	avg	max
0  	100  	0.217143	inf	inf



Evaluating Population: 100%|██████████| 78/78 [02:21<00:00,  1.82s/it]


1  	78   	0.217143	inf	inf


Evaluating Population: 100%|██████████| 67/67 [02:33<00:00,  2.30s/it]

2  	67   	0.217143	inf	inf



Evaluating Population: 100%|██████████| 76/76 [02:29<00:00,  1.96s/it]

3  	76   	0.197818	inf	inf



Evaluating Population: 100%|██████████| 76/76 [02:47<00:00,  2.21s/it]

4  	76   	0.197818	inf	inf



Evaluating Population: 100%|██████████| 72/72 [02:15<00:00,  1.88s/it]

5  	72   	0.19694 	inf	inf



Evaluating Population: 100%|██████████| 67/67 [01:54<00:00,  1.70s/it]

6  	67   	0.19694 	inf	inf



Evaluating Population: 100%|██████████| 69/69 [01:59<00:00,  1.73s/it]

7  	69   	0.195962	inf	inf



Evaluating Population: 100%|██████████| 72/72 [01:53<00:00,  1.58s/it]

8  	72   	0.195962	inf	inf



Evaluating Population: 100%|██████████| 71/71 [01:53<00:00,  1.60s/it]

9  	71   	0.195962	inf	inf



Evaluating Population: 100%|██████████| 85/85 [02:23<00:00,  1.68s/it]

10 	85   	0.194249	inf	inf



Evaluating Population: 100%|██████████| 82/82 [02:25<00:00,  1.77s/it]

11 	82   	0.194249	inf	inf



Evaluating Population: 100%|██████████| 78/78 [02:15<00:00,  1.74s/it]


12 	78   	0.194249	inf	inf


Evaluating Population: 100%|██████████| 81/81 [02:15<00:00,  1.68s/it]

13 	81   	0.193138	inf	inf



Evaluating Population: 100%|██████████| 63/63 [01:47<00:00,  1.71s/it]


14 	63   	0.193138	inf	inf


Evaluating Population: 100%|██████████| 67/67 [02:00<00:00,  1.80s/it]

15 	67   	0.192862	inf	inf



Evaluating Population: 100%|██████████| 84/84 [02:31<00:00,  1.80s/it]

16 	84   	0.19268 	inf	inf



Evaluating Population: 100%|██████████| 73/73 [02:10<00:00,  1.79s/it]

17 	73   	0.19268 	inf	inf



Evaluating Population: 100%|██████████| 68/68 [02:04<00:00,  1.82s/it]

18 	68   	0.19268 	inf	inf



Evaluating Population: 100%|██████████| 76/76 [02:19<00:00,  1.83s/it]

19 	76   	0.191567	inf	inf



Evaluating Population: 100%|██████████| 77/77 [02:19<00:00,  1.82s/it]


20 	77   	0.191567	inf	inf


IndexError: index 1 is out of bounds for axis 0 with size 1

In [12]:
mggp._hof[0]._theta

[array([0.00019957]),
 array([-2.84430258e-05]),
 array([-0.00024055]),
 array([0.00056695]),
 array([-0.00029781]),
 array([-7.97402255e-07]),
 array([0.00085275]),
 array([-0.00072299]),
 array([-2.92731829e-05]),
 array([-0.00109971]),
 array([1.01687359]),
 array([3.23199619e-05]),
 array([-2.58874005e-05]),
 array([-0.00943273]),
 array([-0.00636928]),
 array([-0.00045608])]

In [13]:
print(mggp._hof[0])

1
q13(q15(q5(q5(q13(q15(q3(q5(u2))))))))
q1(q9(q10(q8(q4(q10(q6(y1)))))))
q14(q8(mul(q8(q7(u1)), q2(q14(q1(q4(y1)))))))
u1
q7(mul(mul(q13(q5(q6(q6(u1)))), y1), y1))
u2
q9(q3(u2))
mul(q5(q2(q14(q5(q4(q7(q2(q12(q7(q3(q6(u2))))))))))), q1(q2(q14(q14(q15(q14(q15(q6(q13(y1))))))))))
q8(q7(q9(q13(q15(q6(y1))))))
y1
mul(q2(q13(q10(q6(q7(y1))))), q8(q12(q12(q6(q13(u2))))))
q9(q6(mul(y1, mul(q7(q14(q13(q6(q14(q13(q6(u1))))))), u1))))
q5(q7(q14(q3(q14(q14(q3(y1)))))))
q1(q11(q1(q6(q4(q6(q4(q6(q8(y1)))))))))
q14(mul(y1, u1))

