# Imports

In [1]:
import numpy as np 
import pandas as pd 
import os
from mggp import MGGP

# Execute

In [4]:
dataframes = []

for RT_data in os.listdir('RT_datas'):
    print(f"Lendo o arquivo: {RT_data}")
    data = pd.read_csv(f"RT_datas/{RT_data}")
    data_selected  = data[['ch_AngleSlip____', 'ch_VelLocalX_m_s_', 'ch_VelLocalY_m_s_']]
    dataframes.append(data_selected)

df_result = pd.concat(dataframes, ignore_index=True).dropna()
df_result.columns = ['AngleSlip', 'Vx', 'Vy']
# df_result = df_result.sample(frac=1, random_state=42).reset_index(drop=True) # Lines randomized
df_result.to_csv("angle_slip.csv", index=False)

Lendo o arquivo: RT_data_Job1_2023_07_28_16_41_10_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_36_05_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_41_22_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_46_44_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_11_58_50_Mix.csv
Lendo o arquivo: RT_data_Job1_2023_07_29_12_15_29_Mix.csv


In [2]:
df_train = pd.read_csv("angle_slip.csv").to_numpy()
u, y = (df_train[:, :2], df_train[:, 2:3])

split = 0.8
y_train = y[:int(len(y)*split)]
y_val = y[int(len(y)*split):]

print(len(y_val), len(y_train))

u_train = u[:int(len(u)*split)]
u_val = u[int(len(u)*split):]

print(len(u_val), len(u_train))

60397 241587
60397 241587


In [3]:
df_train = pd.read_csv("angle_slip.csv").to_numpy()
u, y = (df_train[:3500, :2], df_train[:3500, 2:3])

split = 0.9
y_train = y[:int(len(y)*split)]
y_val = y[int(len(y)*split):]

print(len(y_val), len(y_train))

u_train = u[:int(len(u)*split)]
u_val = u[int(len(u)*split):]

print(len(u_val), len(u_train))

mggp = MGGP(inputs=u_train,
            outputs=y_train,
            validation=(u_val, y_val),
            #nDelays=[1, 2, 3, 5, 10, 15, 25, 50],
            nDelays=15,
            generations=50,
            evaluationMode="MSE",
            k=100,
            evaluationType="FreeRun")

mggp.run()

350 3150
350 3150


Evaluating Initial Population: 100%|██████████| 100/100 [01:09<00:00,  1.45it/s]


   	     	          fitness          
   	     	---------------------------
gen	evals	min       	avg	max
0  	100  	0.00643379	inf	inf


Evaluating Population: 100%|██████████| 66/66 [01:00<00:00,  1.10it/s]


1  	66   	0.00643379	inf	inf


Evaluating Population: 100%|██████████| 78/78 [01:15<00:00,  1.03it/s]


2  	78   	0.00505806	inf	inf


Evaluating Population: 100%|██████████| 86/86 [01:35<00:00,  1.11s/it]


3  	86   	0.00505806	inf	inf


Evaluating Population: 100%|██████████| 81/81 [01:36<00:00,  1.19s/it]


4  	81   	0.00100891	inf	inf


Evaluating Population: 100%|██████████| 76/76 [01:31<00:00,  1.20s/it]


5  	76   	0.00100891	inf	inf


Evaluating Population: 100%|██████████| 79/79 [01:27<00:00,  1.11s/it]


6  	79   	0.00100891	inf	inf


Evaluating Population: 100%|██████████| 72/72 [01:20<00:00,  1.11s/it]


7  	72   	0.00100891	inf	inf


Evaluating Population: 100%|██████████| 61/61 [01:11<00:00,  1.17s/it]


8  	61   	0.00100891	inf	inf


Evaluating Population: 100%|██████████| 71/71 [01:27<00:00,  1.24s/it]


9  	71   	0.000758391	inf	inf


Evaluating Population: 100%|██████████| 79/79 [01:32<00:00,  1.17s/it]


10 	79   	0.000758391	inf	inf


Evaluating Population: 100%|██████████| 66/66 [01:15<00:00,  1.14s/it]


11 	66   	0.000758391	inf	inf


Evaluating Population: 100%|██████████| 79/79 [03:47<00:00,  2.88s/it] 


12 	79   	0.000758391	inf	inf


Evaluating Population: 100%|██████████| 74/74 [01:44<00:00,  1.41s/it]


13 	74   	0.000602835	inf	inf


Evaluating Population: 100%|██████████| 75/75 [01:38<00:00,  1.31s/it]


14 	75   	0.000602835	inf	inf


Evaluating Population: 100%|██████████| 69/69 [01:28<00:00,  1.28s/it]


15 	69   	0.000431497	inf	inf


Evaluating Population: 100%|██████████| 80/80 [01:29<00:00,  1.12s/it]


16 	80   	0.000431497	inf	inf


Evaluating Population: 100%|██████████| 65/65 [01:29<00:00,  1.38s/it]


17 	65   	0.000431497	inf	inf


Evaluating Population: 100%|██████████| 78/78 [01:37<00:00,  1.25s/it]


18 	78   	0.000424525	inf	inf


Evaluating Population: 100%|██████████| 75/75 [01:34<00:00,  1.26s/it]


19 	75   	0.000424525	inf	inf


Evaluating Population: 100%|██████████| 71/71 [01:36<00:00,  1.36s/it]


20 	71   	0.000424525	inf	inf


Evaluating Population: 100%|██████████| 72/72 [01:41<00:00,  1.42s/it]


21 	72   	0.000349991	inf	inf


Evaluating Population: 100%|██████████| 79/79 [01:51<00:00,  1.41s/it]


22 	79   	0.000305542	inf	inf


Evaluating Population: 100%|██████████| 85/85 [02:00<00:00,  1.41s/it]


23 	85   	0.000303431	inf	inf


Evaluating Population: 100%|██████████| 74/74 [01:43<00:00,  1.39s/it]


24 	74   	0.000303431	inf	inf


Evaluating Population: 100%|██████████| 77/77 [01:52<00:00,  1.46s/it]


25 	77   	0.000293115	inf	inf


Evaluating Population: 100%|██████████| 68/68 [01:41<00:00,  1.50s/it]


26 	68   	0.000293115	inf	inf


Evaluating Population: 100%|██████████| 71/71 [01:45<00:00,  1.48s/it]


27 	71   	0.000293115	inf	inf


Evaluating Population: 100%|██████████| 70/70 [01:43<00:00,  1.47s/it]


28 	70   	0.000293115	inf	inf


Evaluating Population: 100%|██████████| 75/75 [01:50<00:00,  1.48s/it]


29 	75   	0.000262111	inf	inf


Evaluating Population: 100%|██████████| 81/81 [01:54<00:00,  1.41s/it]


30 	81   	0.000262111	inf	inf


Evaluating Population: 100%|██████████| 78/78 [01:52<00:00,  1.44s/it]


31 	78   	0.000240106	inf	inf


Evaluating Population: 100%|██████████| 78/78 [01:48<00:00,  1.39s/it]


32 	78   	0.000240106	inf	inf


Evaluating Population: 100%|██████████| 80/80 [01:51<00:00,  1.40s/it]


33 	80   	0.000233866	inf	inf


Evaluating Population: 100%|██████████| 76/76 [02:13<00:00,  1.76s/it]


34 	76   	0.000203504	inf	inf


Evaluating Population: 100%|██████████| 76/76 [01:54<00:00,  1.51s/it]


35 	76   	0.000203504	inf	inf


Evaluating Population: 100%|██████████| 72/72 [01:52<00:00,  1.56s/it]


36 	72   	0.000197658	inf	inf


Evaluating Population: 100%|██████████| 67/67 [01:34<00:00,  1.40s/it]


37 	67   	0.000197658	inf	inf


Evaluating Population: 100%|██████████| 78/78 [02:10<00:00,  1.67s/it]


38 	78   	0.000197658	inf	inf


Evaluating Population: 100%|██████████| 77/77 [02:07<00:00,  1.66s/it]


39 	77   	0.000197658	inf	inf


Evaluating Population: 100%|██████████| 79/79 [02:03<00:00,  1.57s/it]


40 	79   	0.000193354	inf	inf


Evaluating Population: 100%|██████████| 70/70 [01:57<00:00,  1.69s/it]


41 	70   	0.000193354	inf	inf


Evaluating Population: 100%|██████████| 68/68 [01:46<00:00,  1.57s/it]


42 	68   	0.000193354	inf	inf


Evaluating Population: 100%|██████████| 79/79 [01:47<00:00,  1.36s/it]


43 	79   	0.000181569	inf	inf


Evaluating Population: 100%|██████████| 64/64 [01:36<00:00,  1.51s/it]


44 	64   	0.000181569	inf	inf


Evaluating Population: 100%|██████████| 75/75 [01:46<00:00,  1.42s/it]


45 	75   	0.00017855 	inf	inf


Evaluating Population: 100%|██████████| 77/77 [01:44<00:00,  1.35s/it]


46 	77   	0.00017855 	inf	inf


Evaluating Population: 100%|██████████| 76/76 [01:44<00:00,  1.38s/it]


47 	76   	0.000178218	inf	inf


Evaluating Population: 100%|██████████| 78/78 [01:50<00:00,  1.41s/it]


48 	78   	0.0001775  	inf	inf


Evaluating Population: 100%|██████████| 72/72 [01:41<00:00,  1.42s/it]


49 	72   	0.000174929	inf	inf


Evaluating Population: 100%|██████████| 71/71 [01:40<00:00,  1.41s/it]


50 	71   	0.000174929	inf	inf
----------- Model -----------
1
q7(q5(mul(q12(mul(mul(q11(y1), q9(q3(u2))), q6(mul(q2(u2), u2)))), q2(q6(q3(q5(q5(q4(mul(mul(q11(y1), q9(q3(u2))), q7(q6(q13(q3(q10(u1)))))))))))))))
q3(q4(mul(q1(q8(q10(u2))), q11(q3(q13(q10(u2)))))))
u2
q8(q13(q3(mul(q3(mul(q8(q15(q15(q5(q2(q12(q15(q2(q12(u1))))))))), q7(q2(u1)))), q7(q2(u1))))))
q13(q15(q4(q10(q10(q4(q10(q10(q2(q11(q2(q11(q12(q10(u1))))))))))))))
q1(q4(u1))
q1(q10(u2))
q2(q5(q3(q3(y1))))
q3(u1)
q2(q3(q3(q2(mul(q6(q11(q15(q15(u2)))), q5(q14(q15(u2))))))))
q15(q5(q1(q2(q7(q2(q6(q2(q7(q1(q6(q12(q5(u2)))))))))))))
u1
y1
mul(q7(q8(u1)), u2)
q4(q2(q1(q5(q1(q11(mul(y1, q3(q11(q7(u2))))))))))

----------- Theta -----------
[array([0.00737399]), array([-4.85920731e-07]), array([0.00918901]), array([0.12122289]), array([-0.00018564]), array([0.0017359]), array([0.00509398]), array([-0.14126945]), array([0.09061604]), array([0.00691464]), array([0.00198263]), array([-0.00403127]), array([-0.01963066]), array([0.9367

In [11]:
mggp = MGGP(inputs=u_train,
            outputs=y_train,
            validation=(u_val, y_val),
            #nDelays=[1, 2, 3, 5, 10, 15, 25, 50],
            nDelays=15,
            generations=20,
            evaluationMode="RMSE",
            k=100,
            evaluationType="MShooting")

mggp.run()

Evaluating Initial Population: 100%|██████████| 100/100 [02:29<00:00,  1.50s/it]

   	     	          fitness          
   	     	---------------------------
gen	evals	min     	avg	max
0  	100  	0.217143	inf	inf



Evaluating Population: 100%|██████████| 78/78 [02:21<00:00,  1.82s/it]


1  	78   	0.217143	inf	inf


Evaluating Population: 100%|██████████| 67/67 [02:33<00:00,  2.30s/it]

2  	67   	0.217143	inf	inf



Evaluating Population: 100%|██████████| 76/76 [02:29<00:00,  1.96s/it]

3  	76   	0.197818	inf	inf



Evaluating Population: 100%|██████████| 76/76 [02:47<00:00,  2.21s/it]

4  	76   	0.197818	inf	inf



Evaluating Population: 100%|██████████| 72/72 [02:15<00:00,  1.88s/it]

5  	72   	0.19694 	inf	inf



Evaluating Population: 100%|██████████| 67/67 [01:54<00:00,  1.70s/it]

6  	67   	0.19694 	inf	inf



Evaluating Population: 100%|██████████| 69/69 [01:59<00:00,  1.73s/it]

7  	69   	0.195962	inf	inf



Evaluating Population: 100%|██████████| 72/72 [01:53<00:00,  1.58s/it]

8  	72   	0.195962	inf	inf



Evaluating Population: 100%|██████████| 71/71 [01:53<00:00,  1.60s/it]

9  	71   	0.195962	inf	inf



Evaluating Population: 100%|██████████| 85/85 [02:23<00:00,  1.68s/it]

10 	85   	0.194249	inf	inf



Evaluating Population: 100%|██████████| 82/82 [02:25<00:00,  1.77s/it]

11 	82   	0.194249	inf	inf



Evaluating Population: 100%|██████████| 78/78 [02:15<00:00,  1.74s/it]


12 	78   	0.194249	inf	inf


Evaluating Population: 100%|██████████| 81/81 [02:15<00:00,  1.68s/it]

13 	81   	0.193138	inf	inf



Evaluating Population: 100%|██████████| 63/63 [01:47<00:00,  1.71s/it]


14 	63   	0.193138	inf	inf


Evaluating Population: 100%|██████████| 67/67 [02:00<00:00,  1.80s/it]

15 	67   	0.192862	inf	inf



Evaluating Population: 100%|██████████| 84/84 [02:31<00:00,  1.80s/it]

16 	84   	0.19268 	inf	inf



Evaluating Population: 100%|██████████| 73/73 [02:10<00:00,  1.79s/it]

17 	73   	0.19268 	inf	inf



Evaluating Population: 100%|██████████| 68/68 [02:04<00:00,  1.82s/it]

18 	68   	0.19268 	inf	inf



Evaluating Population: 100%|██████████| 76/76 [02:19<00:00,  1.83s/it]

19 	76   	0.191567	inf	inf



Evaluating Population: 100%|██████████| 77/77 [02:19<00:00,  1.82s/it]


20 	77   	0.191567	inf	inf


IndexError: index 1 is out of bounds for axis 0 with size 1

In [12]:
mggp._hof[0]._theta

[array([0.00019957]),
 array([-2.84430258e-05]),
 array([-0.00024055]),
 array([0.00056695]),
 array([-0.00029781]),
 array([-7.97402255e-07]),
 array([0.00085275]),
 array([-0.00072299]),
 array([-2.92731829e-05]),
 array([-0.00109971]),
 array([1.01687359]),
 array([3.23199619e-05]),
 array([-2.58874005e-05]),
 array([-0.00943273]),
 array([-0.00636928]),
 array([-0.00045608])]

In [13]:
print(mggp._hof[0])

1
q13(q15(q5(q5(q13(q15(q3(q5(u2))))))))
q1(q9(q10(q8(q4(q10(q6(y1)))))))
q14(q8(mul(q8(q7(u1)), q2(q14(q1(q4(y1)))))))
u1
q7(mul(mul(q13(q5(q6(q6(u1)))), y1), y1))
u2
q9(q3(u2))
mul(q5(q2(q14(q5(q4(q7(q2(q12(q7(q3(q6(u2))))))))))), q1(q2(q14(q14(q15(q14(q15(q6(q13(y1))))))))))
q8(q7(q9(q13(q15(q6(y1))))))
y1
mul(q2(q13(q10(q6(q7(y1))))), q8(q12(q12(q6(q13(u2))))))
q9(q6(mul(y1, mul(q7(q14(q13(q6(q14(q13(q6(u1))))))), u1))))
q5(q7(q14(q3(q14(q14(q3(y1)))))))
q1(q11(q1(q6(q4(q6(q4(q6(q8(y1)))))))))
q14(mul(y1, u1))

